"""Declarative base for ORM models.

All ORM models inherit from :class:`Base`. Alembic imports this module to
discover metadata for autogenerated migrations. No concrete tables are
defined here — models live in :mod:`app.models`.
"""

from __future__ import annotations

from sqlalchemy.orm import DeclarativeBase


class Base(DeclarativeBase):
    """Shared declarative base carrying the SQLAlchemy metadata registry."""
